{{ if .Values.k8gb.validatingAdmissionPolicy.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: k8gb-exposed-ip-annotation
spec:
  policyName: k8gb-exposed-ip-annotation
  matchResources:
    namespaceSelector: {}
  validationActions:
    - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: k8gb-exposed-ip-annotation
spec:
  validations:
    - expression: object.metadata.annotations['k8gb.io/exposed-ip-addresses'].matches('^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$')
      message: The annotation 'k8gb.io/exposed-ip-addresses' must contain a valid IPv4 address
  matchConditions:
    - name: hasExposedIPAddressesAnnotation
      expression: "has(object.metadata.annotations) && 'k8gb.io/exposed-ip-addresses' in object.metadata.annotations"
  matchConstraints:
    resourceRules:
      - apiGroups: ["k8gb.absa.oss"]
        apiVersions: ["v1beta1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["gslbs"]
  failurePolicy: Fail
{{ end -}}
