{{- if .Values.coredns.deployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-coredns
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "chart.labels" . | indent 4  }}
data:
  Corefile: |-
    {{ .Values.k8gb.dnsZone }}:5353 {
        errors
        health
{{- if .Values.k8gb.coredns.extra_plugins }}
{{- range .Values.k8gb.coredns.extra_plugins }}
        {{ . }}
{{- end }}
{{- end }}
        ready
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        k8s_crd {
            filter k8gb.absa.oss/dnstype=local
            negttl {{ .Values.k8gb.dnsZoneNegTTL }}
            loadbalance weight
        }
    }
    {{- with .Values.k8gb.coredns.extraServerBlocks -}}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
{{- end }}
